In [1]:
import numpy as np
import sys

print(f"Python version:  {sys.version}\n"
      f"NumPy version:   {np.__version__}")

rng = np.random.default_rng(42)  # initialise our random number generator

Python version:  3.8.8 (default, Apr 13 2021, 19:58:26) 
[GCC 7.3.0]
NumPy version:   1.19.5


In [2]:
np

<module 'numpy' from '/home/claudia/.local/lib/python3.8/site-packages/numpy/__init__.py'>

In [4]:
np.array([1,2,3])

array([1, 2, 3])

In [5]:
a=np.array([1,2,3])

In [6]:
print(a)

[1 2 3]


In [7]:
type(a)

numpy.ndarray

Array properties

In [9]:
a.size

3

In [10]:
a.shape

(3,)

In [11]:
a.dtype

dtype('int64')

Multidimesional array

In [15]:
b = np.array([[1,2,3,4], [5,6,7,8]])

In [16]:
print(b)

[[1 2 3 4]
 [5 6 7 8]]


# array methods

In [17]:
a.min()

1

In [18]:
b.min()

1

For a n dimensional array we can get the minimum value for every vector in the array

In [19]:
b.min(axis=1)

array([1, 5])

In [20]:
b.sum()

36

In [21]:
b.sum(axis=0)

array([ 6,  8, 10, 12])

In [22]:
b.sum(axis=1)

array([10, 26])

# Array operations

In [23]:
a-42

array([-41, -40, -39])

In [25]:
a/np.pi

array([0.31830989, 0.63661977, 0.95492966])