# Excercises

In [25]:
import numpy as np

In [78]:
rng = np.random.default_rng(42)  # always create a generator with a seed!

### 1. Extract the integer part of a random sample

In [24]:
rng = 10*np.random.rand(2,3)
rng

array([[4.41317027, 6.18389202, 4.19514485],
       [6.51427939, 3.77620491, 8.1470259 ]])

In [23]:
np.array (rng, dtype = "int")

array([[5, 0, 6],
       [6, 1, 7]])

### 2. Create a 5x5 matrix woth 5 on the diagonal

In [26]:
5*np.eye(5,5)

array([[5., 0., 0., 0., 0.],
       [0., 5., 0., 0., 0.],
       [0., 0., 5., 0., 0.],
       [0., 0., 0., 5., 0.],
       [0., 0., 0., 0., 5.]])

### 3. Calculate c
a=rng.random(1234567)

b=rng.random(1234567)

c_i=tan(a_i)\cdot b_i-a_i^{b_i}

for i in [0,1234566]

In [28]:
rng = np.random.default_rng(42)

In [31]:
a=rng.random(1234567)
b=rng.random(1234567)
a

array([0.51006671, 0.94888277, 0.09569171, ..., 0.20594585, 0.81570642,
       0.48265836])

In [33]:
c = np.tan(a)*b-a**b
print(c)

[-0.94251216 -0.68564223 -0.5926123  ... -0.22784624  0.05748215
 -0.27970023]



### 4. Given two arrays a anb b, check if they are equal

a = rng.random(1234567)

b = a.copy()

b[-1] = 23  # artificially make them differ at the very end ;)



In [35]:
a = rng.random(1234567)
b = a.copy()
a==b

array([ True,  True,  True, ...,  True,  True,  True])

In [36]:
b[-1] = 23
a==b

array([ True,  True,  True, ...,  True,  True, False])


### 5. Create the following matrix

1 2 3 4 5 6

1 2 3 4 5 6

1 2 3 4 5 6

1 2 3 4 5 6

1 2 3 4 5 6



In [39]:
a = np.ones((5,6))
b=np.array([1,2,3,4,5,6])
a*b

array([[1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.],
       [1., 2., 3., 4., 5., 6.]])

### 6. Roll two 6-sided dice 100 times and count each individual value

In [74]:
a = np.random.randint(1, 7, 100)    #returns 100 random integers in interval [1,7)
b = np.random.randint(1, 7, 100)
print(a)
print(b)

[6 4 5 5 4 3 1 2 2 6 5 6 3 2 3 2 3 1 5 5 2 4 2 4 5 1 2 6 4 3 5 6 2 4 6 1 5
 6 5 1 6 2 6 1 1 6 5 6 4 4 4 6 2 4 5 3 3 1 2 3 6 3 3 6 3 3 3 2 2 6 3 6 6 5
 2 4 2 4 5 4 5 5 6 5 1 6 2 2 6 1 1 6 6 2 5 2 3 4 4 1]
[6 3 3 6 5 5 3 5 6 2 2 6 1 1 3 5 1 1 5 5 6 3 1 2 1 6 6 6 4 1 5 1 5 5 5 1 1
 6 4 4 1 4 3 4 5 6 2 4 1 6 3 6 6 4 6 2 2 2 3 2 4 3 1 4 2 1 4 2 6 1 2 4 5 4
 4 3 1 2 6 2 2 3 4 5 6 6 3 4 4 5 6 5 2 5 1 3 1 2 1 2]


### 7. Roll five 12-sided dice 123456 times and count each individual value

In [75]:
a = np.random.randint(1, 13, 123456)    #returns 100 random integers in interval [1,7)
b = np.random.randint(1, 13, 123456)
c = np.random.randint(1, 13, 123456)
d = np.random.randint(1, 13, 123456)
e = np.random.randint(1, 13, 123456)

print(a)
print(b)
print(c)
print(d)
print(e)

[ 3  2 11 ... 12 10  7]
[12  7 10 ...  2  7  2]
[ 8  3  3 ... 11  6 10]
[11 11  2 ... 10  9  3]
[9 1 6 ... 6 5 6]


Alternatively, try a for loop

In [77]:
for i in range(5):
    a = np.random.randint(1,13,123456)
    print(a)

[ 7  1  4 ... 10  3 12]
[ 4  7  3 ...  2  9 10]
[ 4  4 12 ...  1  1  6]
[ 5  9 11 ...  1  6  9]
[12  6  9 ...  3  7 10]


### 8. Find the value closest to a given number in an array

a = rng.random(10)

target = 0.23



In [80]:
a = rng.random(10)
target = 0.23
a

array([0.37079802, 0.92676499, 0.64386512, 0.82276161, 0.4434142 ,
       0.22723872, 0.55458479, 0.06381726, 0.82763117, 0.6316644 ])

In [85]:
diff = np.absolute(a -target)
diff.min()

0.002761278215223123

### 9. Create a random array with 10 elements and replace its largest value with 0 

In [99]:
a = rng.random(10)
a


array([0.1523121 , 0.69632038, 0.44615628, 0.38102123, 0.30151209,
       0.63028259, 0.36181261, 0.08764992, 0.1180059 , 0.96189766])

In [100]:
a[np.argmax(a)]=0
a

array([0.1523121 , 0.69632038, 0.44615628, 0.38102123, 0.30151209,
       0.63028259, 0.36181261, 0.08764992, 0.1180059 , 0.        ])

In [101]:
a[np.argmax(a)]=0
a

array([0.1523121 , 0.        , 0.44615628, 0.38102123, 0.30151209,
       0.63028259, 0.36181261, 0.08764992, 0.1180059 , 0.        ])

### 10. Create a checkerboard (8x8, 0s and 1s)¶

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0

0 1 0 1 0 1 0 1

1 0 1 0 1 0 1 0



In [106]:
a = [0,1,0,1,0,1,0,1]
b = [1,0,1,0,1,0,1,0]
checkboard = (a,b,a,b,a,b,a,b)
checkboard

([0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0],
 [0, 1, 0, 1, 0, 1, 0, 1],
 [1, 0, 1, 0, 1, 0, 1, 0])

### 11. Calculate the diagonal of a dot product

## Nearest point excercise
Given an array of points in 3D, find the nearest point for each one